site_name: OCaml scikit-learn interface
docs_dir: doc/
site_dir: html_doc/
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - instant
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: "2-3"
plugins:
  - search
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
repo_name: lehy/ocaml-sklearn
repo_url: https://github.com/lehy/ocaml-sklearn
